app/models.py
from datetime import datetime

from flask_security import RoleMixin, UserMixin

from . import db


roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('roles.id')))


class Role(db.Model, RoleMixin):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    username = db.Column(db.String(24))

    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(45))
    current_login_ip = db.Column(db.String(45))
    login_count = db.Column(db.Integer())

    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))

    github = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    location = db.Column(db.String(64))

    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

    submissions = db.relationship('Submission', backref='submitter', lazy='dynamic')


class Challenge(db.Model):
    __tablename__ = 'challenges'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    body = db.Column(db.Text())
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)


class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(24), unique=True)


class Submission(db.Model):
    __tablename__ = 'submissions'
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(255), unique=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    submitter_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/forms.py
from flask_security.forms import RegisterForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class ExtendedRegisterForm(RegisterForm):
    username = StringField('Username', [DataRequired(), Length(max=24)])

app/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_security import Security, SQLAlchemyUserDatastore
from flask_sqlalchemy import SQLAlchemy

from app.forms import ExtendedRegisterForm
from config import config
from .hash_utils import create_hashid

bootstrap = Bootstrap()
db = SQLAlchemy()
security = Security()
admin = Admin(name='python challenges', template_mode='bootstrap3')
mail = Mail()
moment = Moment()


def create_app(config_name):
    '''
    Creates the app at run time, allowing the loading of correct configuration settings
    :param config_name: Runtime Config
    :return: Running Flask app
    '''
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    moment.init_app(app)

    from .models import User, Role

    # Initialize Flask-Security
    from app.forms import ExtendedRegisterForm

    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    security.init_app(app, user_datastore, confirm_register_form=ExtendedRegisterForm)

    # Initialize Flask-Admin
    admin.init_app(app)

    # Export hashid creation to jinja templates for use
    app.jinja_env.globals.update(create_hashid=create_hashid)

    # Blueprint registrations go here
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .admin_sec import admin_sec as admin_blueprint
    app.register_blueprint(admin_blueprint)

    return app

app/admin_sec/__init__.py
from flask import Blueprint

admin_sec = Blueprint('admin_sec', __name__)

from . import views

app/admin_sec/views.py
from flask_admin.contrib.sqla import ModelView

from .. import admin
from .. import db
from ..models import User, Role, Challenge, Tag

admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Role, db.session))
admin.add_view(ModelView(Challenge, db.session))
admin.add_view(ModelView(Tag, db.session))

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, url_for, request, current_app
from flask_security import current_user, login_required

from . import main
from ..models import Challenge, User
from ..hash_utils import decode_hashid


def get_challenge(challenge_id):
    challenge = Challenge.query.filter_by(id=challenge_id).first()
    return challenge


def get_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    return user


@main.route('/')
def index():
    current_challenge = Challenge.query.order_by(Challenge.timestamp.desc()).first()
    page = request.args.get('page', 1, type=int)
    pagination = Challenge.query.order_by(Challenge.timestamp.desc()).paginate(page, per_page=5, error_out=False)
    past_challenges = pagination.items

    return render_template('index.html', current_challenge=current_challenge, past_challenges=past_challenges, pagination=pagination)


@main.route('/<challenge_id>')
def challenge_detailed(challenge_id):
    challenge = get_challenge(challenge_id)

    return render_template('challenge.html', challenge=challenge)


@main.route('/profile/<string:hashid>')
@login_required
def profile(hashid):
    user_id = decode_hashid(hashid)
    user = get_user(user_id)

    return render_template('profile.html', user=user)


@main.route('/submissions/<string:hashid>')
@login_required
def user_submissions(hashid):
    user_id = decode_hashid(hashid)
    user = get_user(user_id)

    return render_template('user_submissions.html', user=user)


@main.route('/submit/<challenge_id>/<string:hashid>', methods=['GET', 'POST'])
@login_required
def submit_challenge(challenge_id, hashid):
    user_id = decode_hashid(hashid)

    challenge = get_challenge(challenge_id)
    user = get_user(user_id)

    return render_template('submit.html', user=user, challenge=challenge)


@main.route('/edit_profile/<string:hashid>')
@login_required
def edit_profile(hashid):
    user_id = decode_hashid(hashid)
    user = get_user(user_id)

    return render_template('edit_profile.html', user=user)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
            page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/challenge.css') }}">
{% endblock %}

{% block navbar %}
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-btn-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">python challenges</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-btn-collapse">
                    {% if current_user.is_authenticated %}
                        <ul class="nav navbar-nav">
                            <li><a href="{{ url_for('main.index') }}">Challenges</a></li>
                            <li><a href="{{ url_for('main.user_submissions', hashid=create_hashid(current_user.id)) }}">Submissions</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.username }}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('main.profile', hashid=create_hashid(current_user.id)) }}">Profile</a></li>
                                    <li><a href="{{ url_for('security.logout') }}">Logout</a></li>
                                </ul>
                        </ul>
                    {% else %}
                        <div class="nav navbar-right">
                            <ul class="list-inline">
                                <li><a role="button" href="{{ url_for('security.login') }}" class="btn btn-default navbar-btn">Sign In</a></li>
                                <li><a role="button" href="{{ url_for('security.register') }}" class="btn btn-info navbar-btn">Register</a></li>
                            </ul>
                        </div>
                    {% endif %}
            </div>
        </nav>
    </div>

{% endblock %}

    <div class="container">

    </div>

{% block content %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/challenge.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ challenge.name }}</h1>
    <h3>{{ moment(challenge.timestamp).format('MMM Do YY') }}</h3>
    <p>{{ challenge.body }}</p>
</div>
{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<h1>This is where {{ user.email }} will edit their information</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Current Challenge</h1>
            <h3><a href="{{ url_for('main.challenge_detailed', challenge_id=current_challenge.id) }}">{{ current_challenge.name }}</a></h3>
            <p>{{ current_challenge.body }}</p>
            {% if current_user.is_authenticated %}
                <a class="btn btn-default" role="button" href="{{ url_for('main.submit_challenge', challenge_id=current_challenge.id, hashid=create_hashid(current_user.id)) }}">Submit Your Code</a>
            {% else %}
                <a class="btn btn-default" role="button" href="{{ url_for('security.login') }}">Log In to Submit</a>
            {% endif %}
        </div>

        {% for challenge in past_challenges %}
            <ul class="challenges">
                <li class="challenge">
                    <div class="challenge-date">{{ moment(challenge.timestamp).fromNow() }}</div>
{#                    <div class="challenge-date">{{ challenge.timestamp }}</div>#}
                    <div class="challenge-name">
                        <a href="{{ url_for('main.challenge_detailed', challenge_id=challenge.id) }}">{{ challenge.name }}</a>
                    </div>
                    <div class="challenge-body">{{ challenge.body }}</div>
                </li>
            </ul>
        {% endfor %}
        {{ macros.pagination_widget(pagination, '.index') }}


    </div>

{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>This will be {{ user.email }}'s profile</h1>

    <a href="{{ url_for('main.edit_profile', hashid=create_hashid(user.id)) }}">Edit Profile</a>


{% endblock %}

app/templates/security/change_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(change_password_form) }}

    </div>

{% endblock %}

app/templates/security/forgot_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(forgot_password_form) }}

    </div>

{% endblock %}

app/templates/security/login_user.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(login_user_form) }}

    </div>

{% endblock %}

app/templates/security/register_user.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">

        {% from "security/_macros.html" import render_field_with_errors, render_field %}
        {% include "security/_messages.html" %}

        <form class="form form-basic" method="post" role="form" action="{{ url_for_security('register') }}" name="register_user_form">
            {{ register_user_form.hidden_tag() }}
            {{ wtf.form_errors(register_user_form, hiddens="only") }}
            {{ wtf.form_field(register_user_form.email) }}
            {{ wtf.form_field(register_user_form.username) }}
            {{ wtf.form_field(register_user_form.password) }}
            {% if register_user_form.password_confirm %}
                {{ wtf.form_field(register_user_form.password_confirm) }}
            {% endif %}
            {{ wtf.form_field(register_user_form.submit) }}
        </form>

        <ul class="list-unstyled">
            <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
        </ul>

    </div>

{% endblock %}

app/templates/security/reset_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(reset_password_form) }}

    </div>

{% endblock %}

app/templates/security/send_confirmation.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(send_confirmation_form) }}

    </div>

{% endblock %}

app/templates/security/send_login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    <div class="container">
        {{ wtf.quick_form(send_login_form) }}

    </div>

{% endblock %}

app/templates/submit.html
{% extends 'base.html' %}

{% block content %}
<h1> This will be {{ user.email }}'s submission to {{ challenge.name }}</h1>
{% endblock %}

app/templates/user_submissions.html
{% extends 'base.html' %}

{% block content %}
<h1>This will be {{ user.email }}'s submissions</h1>
{% endblock %}